import fs from 'fs';

try {
    // Attempt to read as UTF-16LE (common PowerShell output)
    let wkt = fs.readFileSync('korea_wkt.txt', { encoding: 'utf16le' });
    if (!wkt.trim().startsWith('MULTIPOLYGON')) {
        // Fallback to utf-8 if it wasn't utf16le
        wkt = fs.readFileSync('korea_wkt.txt', { encoding: 'utf8' });
    }

    wkt = wkt.trim();

    // Validate slightly
    if (!wkt.startsWith('MULTIPOLYGON') && !wkt.startsWith('POLYGON')) {
        console.error("Invalid WKT format:", wkt.substring(0, 50));
        process.exit(1);
    }

    const sql = `
-- Enable PostGIS
create extension if not exists postgis;

-- Create Geography Table
create table if not exists korea_geography (
  id bigint generated by default as identity primary key,
  geog geography(MULTIPOLYGON, 4326) not null
);

-- Insert Data (Clear old data first to avoid duplicates if re-run)
truncate table korea_geography;

insert into korea_geography (geog)
values (ST_GeomFromText('${wkt}', 4326));

-- Index for performance
create index if not exists korea_geography_geog_idx on korea_geography using gist (geog);

-- RPC Function for Land Check
create or replace function check_is_on_land(lat double precision, lng double precision)
returns boolean
language plpgsql
security definer
as $$
begin
  -- Check if the point intersects with the stored polygon
  return exists (
    select 1 
    from korea_geography
    where ST_Intersects(
      geog, 
      ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography
    )
  );
end;
$$;
`;

    fs.writeFileSync('setup_land_check.sql', sql, 'utf8');
    console.log('setup_land_check.sql generated successfully.');

} catch (e) {
    console.error("Error generating SQL:", e);
}
